### ISSUE TITLE
kickassembler export syntax wrong?

### ISSUE THREAD

**Issue by nurpax** [Esshahn/spritemate#110]
When I export sprites in Kick ass format, spritemate.com generates something like this:

```
sprite_1
.byte $00,$20,$00,$00,$2a,$00,$00,$82
.byte $00,$00,$82,$00,$02,$00,$80,$02
```

but the label syntax doesn't look correct.  At least on my KickAssembler, it'd require 

sprite_1:

Leading to this error:

```
sprite_1
^

Error: Pseudo command 'sprite_1' not defined
at line 10, column 1 in number-sprite.inc
```

Also it might be a good idea to add an .align 64 statement before the label?

**Comment by Esshahn** [comment]
Thank you for the bug report. It will take me a while till I can dedicate time for spritemate again, but it will be fixed - cheers!

**Comment by Esshahn** [comment]
actually I just fixed the missing colon. Thanks for making me want to look into the code again ;)
