### ISSUE TITLE
is node_modules checked in intentionally?

### ISSUE THREAD

**Issue by nurpax** [Esshahn/spritemate#114]
I'd expect yarn or npm to populate node_modules.  It should be pulled down automatically based on what's in package.json when you run "yarn" or "npm i".

**Comment by nurpax** [comment]
I'll send a PR.  Looks like it builds and works just fine even without the node_modules directory :)

**Comment by Esshahn** [comment]
Once you took a look at my code you'll understand that my coding level is noobish at best. Therefore I wouldn't even know how to handle node_modules the right way ;)
