### ISSUE TITLE
export asm source with binary notation

### ISSUE THREAD

**Issue by svnt** [Esshahn/spritemate#118]
a option to export sprite as asm with binary notaion would be great
Helpfull do edit hires sprites in source.

like:

.byte %11111111,%00000000,%00000011
.byte %11111111,%00000000,%00000001
.byte %11111111,%00000000,%00000000
.byte %11100111,%00000000,%00000000
.byte %11100111,%00000000,%00000000
.byte %11111111,%00000000,%00000000
.byte %11111111,%00000000,%00000000
.byte %11111111,%00000000,%00000000
.byte %00000000,%00000000,%00000000
.byte %00000000,%00000000,%00000000
.byte %00000000,%00000000,%00000000
.byte %00000000,%00000000,%00000000
.byte %00000000,%00000000,%00000000
.byte %00000000,%00000000,%00000000
.byte %00000000,%00000000,%00000000
.byte %00000000,%00000000,%00000000
.byte %00000000,%00000000,%00000000
.byte %00000000,%00000000,%00000000
.byte %00000000,%00000000,%00000000
.byte %10000000,%00000000,%00000001
.byte %11000000,%00000000,%00000011

**Comment by Esshahn** [comment]
Thank you for the suggestion svnt, I'll put it on my list

**Comment by Esshahn** [comment]
für den Source-Export 24 Binärziffern verwenden. Zum einen wie oben wegen der leichteren Erkennung bzw. Unterscheidung, und außerdem ermöglicht das dann irgendwelche Last-Minute-Änderungen. In den ACME-Docs existiert dafür das SpriteLine-Makro, beim Kickassembler ist sicher ähnliches möglich:
Quellcode
; define a pixel row of a C64 hardware sprite
!macro SpriteLine .v {
!by .v >> 16, (.v >> 8) & 255, .v & 255
}
; define a C64 hardware sprite
; 765432107654321076543210
+SpriteLine %........................
+SpriteLine %.#......................
+SpriteLine %.##.....................
+SpriteLine %.###....................
+SpriteLine %.####...................
+SpriteLine %.#####..................
+SpriteLine %.######.................
+SpriteLine %.#######................
+SpriteLine %.########...............
+SpriteLine %.#########..............
+SpriteLine %.########...............
+SpriteLine %.######.................
+SpriteLine %.######.................
+SpriteLine %.##..##.................
+SpriteLine %.#....##................
+SpriteLine %......##................
+SpriteLine %.......##...............
+SpriteLine %.......##...............
+SpriteLine %........##..............
+SpriteLine %........##..............
+SpriteLine %........................
!byte 0 ; pad to 64-byte block

**Comment by Esshahn** [comment]
Implemented.
