### ISSUE TITLE
Menu bar sometimes becomes unresponsive

### ISSUE THREAD

**Issue by Esshahn** [Esshahn/spritemate#133]
Every now and then it seems the menu bar would not react anymore.
It does register clicks, but there's no menu dropdowns anymore.

**Comment by leissa** [comment]
For me the menu bar doesn't work at all. Running Linux and tried both current Firefox and current Chromium.

**Comment by Esshahn** [comment]
Thanks for the feedback. I need to look into this.

**Comment by Esshahn** [comment]
Can you give me more details about your configuration @leissa ?

**Comment by leissa** [comment]
```
Mozilla Firefox 66.0.2
Chromium 73.0.3683.86 Arch Linux
$ uname -r
5.0.5-arch1-1-ARCH
```
Latest version *does* work in chromium.
What else do you need to know?

**Comment by Esshahn** [comment]
Thanks for the quick response. I still can't reproduce the issue it seems. Tested on Ubuntu, Mac, Win, Chrome, Firefox, Safari... I can only imagine it being some race condition. I haven't updated Spritemate in a while, so if it works now, it's not because of any fixes. Puzzled.

**Comment by leissa** [comment]
Just did some debugging. For Firefox content blocking is responsible:
```
The resource at “https://www.google-analytics.com/analytics.js” was blocked because content blocking is enabled.
```

**Comment by Esshahn** [comment]
Great find! Cheers for the support @leissa

**Comment by Esshahn** [comment]
closing
