### ISSUE TITLE
when loading a file into spritemate, spritemate should show the filename somewhere

### ISSUE THREAD

**Issue by nurpax** [Esshahn/spritemate#137]
or maybe I missed it?

not knowing what file I loaded makes it difficult to work with many files.  for example, loading an .spm and saving as .spd.. 

maybe this is some sort of limitation of the upload/download "save".

**Comment by Esshahn** [comment]
Interesting idea - never came to my mind actually.
Haven't worked on it for way too long...

**Comment by nurpax** [comment]
It's by far the easiest thing to get running on a Mac so that's what I've been using in my demo project.  So thanks for having made it :)

**Comment by Esshahn** [comment]
Speaking of I just spend my last two hours in petmate.... :D

**Comment by Esshahn** [comment]
implemented in new beta
