### ISSUE TITLE
sprite invert colors seem funky

### ISSUE THREAD

**Issue by nurpax** [Esshahn/spritemate#142]
inverting colors after switching a sprite from single color to multicolor and then drawing with a bit with multicolor colors seems to put spritemate into some state that then fails to invert the sprite.

e.g., before:

![image](https://user-images.githubusercontent.com/297823/56997400-58d0b600-6bb0-11e9-991b-bc69a84a9002.png)

after (all green, would expect the green pixels from the original to be gray):

![image](https://user-images.githubusercontent.com/297823/56997434-76058480-6bb0-11e9-82cd-5933aab87d03.png)

it's some combination of switches between single and multicolor that trigger this.  probably just creating a single color, then switching to multicolor, drawing with multicolor color, then switching to single color and inverting.

probably not much of a big deal since it's not really common to switch between these formats.  but looks like there might be some funny inconsistency bug.

**Comment by Esshahn** [comment]
Thank you for the issue report.
I am aware that multicolor and inverting does sometimes look weird, especially after mc colors get converted to single colors again. I've compared my approach to SpritePad, and it seems to behave similar.

The invert code is pretty straight forward, for every pixel it does

````
        if (pixel == 0) pixel_inverted = 1;
        if (pixel == 1) pixel_inverted = 0;
        if (pixel == 2) pixel_inverted = 3;
        if (pixel == 3) pixel_inverted = 2;
````

0 = transparent
1 = main color
2 = mc 1
3 = mc 2

What I didn't quite get from your description is, if the invert routine fails completely?
That part would be more interesting, but I couldn't reproduce that yet.

**Comment by nurpax** [comment]
Well it fails quite completely in single color. You can see the screenshot. It turns everything to green. 

You probably should treat the pixel data differently depending on mode. Eg. if it’s in single color mode, just invert the bits.

**Comment by Esshahn** [comment]
> Well it fails quite completely in single color. You can see the screenshot. It turns everything to green.

Hmm. I can't reproduce that. Can you reproduce the steps for me?

I think the biggest issue is that my internal format has the colors represented as 0,1,2,3 instead of 00, 01, 10, 11. Then I could simply invert the bits just as you described. Changing that internal format would be a huge thing, it happens everywhere, scared to touch that...

**Comment by Esshahn** [comment]
Thinking about all the quirks and hacks I did just to make my data structure work makes me wonder why I didnt do bits right from the start. Clearly the right thing to do.

**Comment by nurpax** [comment]
Repro instructions:

1. Load up spritemate.com
2. Draw with default color
3. Convert current sprite  to MC
4. Paint some pixels with multicolor color 1
5. Convert to single color
6. Invert

It looks like only the pixels drawn originally in SC mode get inverted.  The MC colors do get converted to single colors but invert doesn't apply to those pixels.

**Comment by Esshahn** [comment]
Cheers.
I've added a check for multicolor and treat it differently. This is more consistant now, but still not the best solution. That would be to have a proper bit representation of the data. This is a bigger task though and has to be dealt by a more motivated me sometime in the future :D

**Comment by nurpax** [comment]
Thanks! I’d only refactor it if it enables you to add some other new feature easier.
