### ISSUE TITLE
nice 2 have features

### ISSUE THREAD

**Issue by alexgoldblat** [Esshahn/spritemate#98]
Hi my dear bro'  at last i had some time to explore your top cool tool . my suggestion:
1. to put icon in on top of your website. on the listing of dozens of website , it will be easy to find easy :+1: 
2.  when i press "Setting" (i was curious to know what is means) - Espace don't get back. could be nice
if escape always get back to previous screen without changes.
3. for me i think it's good to include a double click on the cell clear the cell . when i put unwanted fill in the cell , i need to go the Transparent choose "black" and click again to clear it. a bit awkward , double click i think will be more easier to clear.
4. there is no multiply select of sprites. if i want to run "shift-left" for instance for more than 1 sprite , i can't do it now. maybe on development ? 
5. little hint - could be nice  for lazy ppl for me ,when i point (on mouseover) the color , it will display a little caption with the color , i always (!) have trouble if it's Drak Gray or just Light Gray . if its not a big problem for yo. i think that's all for now :)   thank you for developing this cool Sprite editor

**Comment by Esshahn** [comment]
Thanks Alex for the suggestions!

1. you mean a favicon?
2. good idea
3. double click is hardly reliable for web apps. but you can press the shift key when clicking, which deletes the pixel. almost as fast. plus, keys 1-4 switch between the colors
4. currently there is not enough functionality for multiple selects. I can only come up with "multiple delete" or "multiple individual color". I will think about it though.
5. funny enough, this would probably break my code at many places. I will implement this when I refactored my color management

**Comment by alexgoldblat** [comment]
1. yepp....
2. keys 1-4 don't seems to work :( i dunno maybe i did some function which halt the function to work properly. shift + click clear the cell ? okay... pls add to description or guide lines so ppl will know that. ha-ha !  its pretty critical for ppl to know but maybe i am the dumb who don't really notice that.
3.  yep..its enough !  multiple delete+ mulitple individual colors could be handy Ingo! 
4.  thanks!! you are ....awesome ;-)
